package credential

const (
	intGenISISPublicationSecurityProfileBQ96Q32V4   = "PUBLICATION-BQ96-32-V4"
	intGenISISPublicationSecurityProfileBQ96Q96V4   = "PUBLICATION-BQ96-96-V4"
	intGenISISPublicationSecurityProfileWF128V4     = "PUBLICATION-WF128-V4"
	intGenISISPublicationSecurityProfileBQ128Q64V4  = "PUBLICATION-BQ128-64-V4"
	intGenISISPublicationSecurityProfileBQ128Q128V4 = "PUBLICATION-BQ128-128-V4"
)

func intGenISISPublicationSecurityProfileSpecsV4() []IntGenISISSecurityProfileSpec {
	const commonNotes = "Publication-v4 proof-only CROM policy; no complete-system or QROM claim."
	return []IntGenISISSecurityProfileSpec{
		{
			Label:                      intGenISISPublicationSecurityProfileBQ96Q32V4,
			Mode:                       SecurityModeResidualAtBudget,
			ROM:                        ROMModelCROM,
			TargetBits:                 96,
			CoreBitsRequired:           96,
			ROQueryCapScope:            ROQueryCapAggregateComposedGame,
			AggregateROQueryCapLog2:    32,
			AggregateROQueryCapLog2Set: true,
			MinDECSHashBits:            168,
			MinDECSTapeBits:            136,
			MinFSCollisionBits:         168,
			MinFSOutputBits:            168,
			MinSaltBits:                160,
			MinPRFTagElements:          9,
			SeedSlots:                  IntGenISISPRFSeedLen,
			PackedKeyCoords:            IntGenISISPRFPoseidonKeyLen,
			Status:                     SecurityProfileProofOnly,
			Notes:                      commonNotes,
		},
		{
			Label:                      intGenISISPublicationSecurityProfileBQ96Q96V4,
			Mode:                       SecurityModeResidualAtBudget,
			ROM:                        ROMModelCROM,
			TargetBits:                 96,
			CoreBitsRequired:           96,
			ROQueryCapScope:            ROQueryCapAggregateComposedGame,
			AggregateROQueryCapLog2:    96,
			AggregateROQueryCapLog2Set: true,
			MinDECSHashBits:            296,
			MinDECSTapeBits:            200,
			MinFSCollisionBits:         296,
			MinFSOutputBits:            296,
			MinSaltBits:                160,
			MinPRFTagElements:          9,
			SeedSlots:                  IntGenISISPRFSeedLen,
			PackedKeyCoords:            IntGenISISPRFPoseidonKeyLen,
			Status:                     SecurityProfileProofOnly,
			Notes:                      commonNotes,
		},
		{
			Label:              intGenISISPublicationSecurityProfileWF128V4,
			Mode:               SecurityModeQueryWorkFactor,
			ROM:                ROMModelCROM,
			TargetBits:         128,
			CoreBitsRequired:   128,
			ROQueryCapScope:    ROQueryCapAggregateComposedGame,
			MinDECSHashBits:    256,
			MinDECSTapeBits:    136,
			MinFSCollisionBits: 256,
			MinFSOutputBits:    256,
			MinSaltBits:        256,
			MinPRFTagElements:  13,
			SeedSlots:          IntGenISISPRFSeedLen,
			PackedKeyCoords:    IntGenISISPRFPoseidonKeyLen,
			Status:             SecurityProfileProofOnly,
			Notes:              commonNotes,
		},
		{
			Label:                      intGenISISPublicationSecurityProfileBQ128Q64V4,
			Mode:                       SecurityModeResidualAtBudget,
			ROM:                        ROMModelCROM,
			TargetBits:                 128,
			CoreBitsRequired:           128,
			ROQueryCapScope:            ROQueryCapAggregateComposedGame,
			AggregateROQueryCapLog2:    64,
			AggregateROQueryCapLog2Set: true,
			MinDECSHashBits:            264,
			MinDECSTapeBits:            200,
			MinFSCollisionBits:         264,
			MinFSOutputBits:            264,
			MinSaltBits:                192,
			MinPRFTagElements:          10,
			SeedSlots:                  IntGenISISPRFSeedLen,
			PackedKeyCoords:            IntGenISISPRFPoseidonKeyLen,
			Status:                     SecurityProfileProofOnly,
			Notes:                      commonNotes,
		},
		{
			Label:                      intGenISISPublicationSecurityProfileBQ128Q128V4,
			Mode:                       SecurityModeResidualAtBudget,
			ROM:                        ROMModelCROM,
			TargetBits:                 128,
			CoreBitsRequired:           128,
			ROQueryCapScope:            ROQueryCapAggregateComposedGame,
			AggregateROQueryCapLog2:    128,
			AggregateROQueryCapLog2Set: true,
			MinDECSHashBits:            392,
			MinDECSTapeBits:            264,
			MinFSCollisionBits:         392,
			MinFSOutputBits:            392,
			MinSaltBits:                192,
			MinPRFTagElements:          10,
			SeedSlots:                  IntGenISISPRFSeedLen,
			PackedKeyCoords:            IntGenISISPRFPoseidonKeyLen,
			Status:                     SecurityProfileProofOnly,
			Notes:                      commonNotes,
		},
	}
}
